# Generated by Django 5.1.7 on 2025-03-26 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controlador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('RELE', 'RELE'), ('ELECTRO-VALVULA', 'ELECTRO-VALVULA')], max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('controlador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.controlador')),
            ],
        ),
        migrations.CreateModel(
            name='ControlWebActuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actuador')),
            ],
        ),
        migrations.CreateModel(
            name='ControlWebControlador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('controlador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.controlador')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialActuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.actuador')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('NIVEL-ULTRASONICO', 'NIVEL-ULTRASONICO'), ('NIVEL-PERA', 'NIVEL-PERA'), ('CAUDAL', 'CAUDAL'), ('CA', 'CA'), ('CC', 'CC'), ('VA', 'VA'), ('VC', 'VC'), ('SWITCH', 'SWITCH')], max_length=20)),
                ('unidad_medida', models.CharField(help_text='Ejemplo: °C, %, Pa, lux', max_length=50)),
                ('valor_actual', models.FloatField(default=0.0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('controlador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.controlador')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
